<?php

/*
 * Auto-generated by libasynql-fx
 * Created from mysql.sql
 */

declare(strict_types=1);

namespace alvin0319\AdvancedBan;

use Generator;
use poggit\libasynql\DataConnector;
use SOFe\AwaitGenerator\Await;

final class Database{
	public function __construct(private DataConnector $conn){ }

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:33
	 *
	 * @param string $deviceId
	 * @param int    $expireAt
	 * @param string $reason
	 * @param string $issuer
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function banDevice(string $deviceId, int $expireAt, string $reason, string $issuer) : Generator{
		$this->conn->executeInsert("advancedban.ban_device", ["deviceId" => $deviceId, "expireAt" => $expireAt, "reason" => $reason, "issuer" => $issuer], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:18
	 *
	 * @param string $name
	 * @param int    $expireAt
	 * @param string $reason
	 * @param string $issuer
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function banName(string $name, int $expireAt, string $reason, string $issuer) : Generator{
		$this->conn->executeInsert("advancedban.ban_name", ["name" => $name, "expireAt" => $expireAt, "reason" => $reason, "issuer" => $issuer], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:46
	 *
	 * @param string $name
	 * @param string $deviceIds
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function createSession(string $name, string $deviceIds) : Generator{
		$this->conn->executeInsert("advancedban.create_session", ["name" => $name, "deviceIds" => $deviceIds], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:55
	 *
	 * @param string $name
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getSession(string $name) : Generator{
		$this->conn->executeSelect("advancedban.get_session", ["name" => $name], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:8
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initDeviceBan() : Generator{
		$this->conn->executeChange("advancedban.init_device_ban", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:5
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initNameBan() : Generator{
		$this->conn->executeChange("advancedban.init_name_ban", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:11
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initPlayer() : Generator{
		$this->conn->executeChange("advancedban.init_player", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:41
	 *
	 * @param string $deviceId
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function isBannedDevice(string $deviceId) : Generator{
		$this->conn->executeSelect("advancedban.is_banned_device", ["deviceId" => $deviceId], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:26
	 *
	 * @param string $name
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function isBannedName(string $name) : Generator{
		$this->conn->executeSelect("advancedban.is_banned_name", ["name" => $name], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:37
	 *
	 * @param string $deviceId
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function pardonDevice(string $deviceId) : Generator{
		$this->conn->executeChange("advancedban.pardon_device", ["deviceId" => $deviceId], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:22
	 *
	 * @param string $name
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function pardonName(string $name) : Generator{
		$this->conn->executeChange("advancedban.pardon_name", ["name" => $name], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql.sql:51
	 *
	 * @param string $name
	 * @param string $deviceIds
	 *
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function updateSession(string $name, string $deviceIds) : Generator{
		$this->conn->executeChange("advancedban.update_session", ["name" => $name, "deviceIds" => $deviceIds], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}
}
